foodapp/food/urls.py
from . import views
from django.urls import path

app_name='food'
urlpatterns = [
    #food/
    path('',views.IndexClassView.as_view(),name='index'),
    #food/item
    path('item/',views.item,name='item'),
    #food/id
    path('<int:pk>/',views.FoodDetails.as_view(),name="details"),
    #adding items
    path('add',views.AddItem.as_view(),name='add_item'),
    #edit items
    path('update/<int:id>/',views.update_item,name='update'),
    #delete items
    path('delete/<int:id>/',views.delete_item,name='delete_item'),

]

foodapp/foodapp/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_view
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_view.register,name="register"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_view.profile_page,name="profile"),

]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodapp/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=300)
    item_price=models.IntegerField() 
    item_img=models.CharField(max_length=500,default='https://theme-assets.getbento.com/sensei/2f8309a.sensei/assets/images/catering-item-placeholder-704x520.png')
    
    def get_absolute_url(self):
        return reverse("food:details", kwargs={"pk": self.pk})
    

foodapp/users/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    img = models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

foodapp/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields ='__all__'

foodapp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password1','password2']

foodapp/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import ItemForm
from .models import Item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView

# Create your views here.
#function view
'''
def index(request):
    item_list=Item.objects.all()
    context={
        'item_list':item_list,
    }
    return render(request,'food/index.html',context)

def details(request,item_id):
    item_list=Item.objects.get(pk=item_id)
    context={
        'item':item_list,
    }
    return render(request,'food/details.html',context)

def add_item(request):
form=ItemForm(request.POST or None)
if form.is_valid():
    form.save()
    return redirect('food:index')

return render(request,'food/item_form.html',{'form':form})


'''

def item(request):
    return HttpResponse("Item View")


def update_item(request,id):
    item=Item.objects.get(id=id)
    form= ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item_form.html',{'form':form,'item':item})

def delete_item(request,id):
    item=Item.objects.get(id=id)
    if request.method=='POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/delete_item.html',{'item':item})

#class view for details
class FoodDetails(DetailView):
    model=Item
    template_name='food/details.html'

#class view for listing items
class IndexClassView(ListView):
    model=Item
    template_name='food/index.html'
    context_object_name='item_list'

#class view for adding items
class AddItem(CreateView):
    model=Item
    fields=['item_name','item_desc','item_price','item_img']
    template_name: 'food/item_form.html'

    def form_valid(self, form):
        form.instance.user_name=self.request.user

        return super().form_valid(form)


foodapp/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method =="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, account created')
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profile_page(request):
    return render(request,'users/profile.html')

foodapp/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% block title %}
            
        {% endblock %}
        
        <link rel="stylesheet" href="{% static 'food/style.css' %}">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>

            <div class="navbar">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link active" href="{% url 'food:add_item' %}">Add Item</a>
                    <a class="nav-item nav-link active" href="{% url 'logout' %}">Logout </a>
                    <a class="nav-item nav-link active" href="{% url 'profile' %}">{{ user.username }}</a>
                {% else %}
                    <a class="nav-item nav-link active" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link active" href="{% url 'register' %}">SignUp</a>
                {% endif %}
            </div>
        </nav>
        <br/>
        {% if messages %}
            {%for message in messages%}
            <div class="alert alert-{{message.tags}}">
                {{ message }}
            </div>
            {%endfor%}
        {%endif%}
        {% block body%}

        {% endblock%}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>


foodapp/food/templates/food/delete_item.html
<form method="POST">
    {% csrf_token %}
    <h2>Confirmation to delete item</h2>
    <button type="submit">Confirm</button>
</form>

foodapp/food/templates/food/details.html
{% extends 'food/base.html' %}
{% block head %}
    <title>{{item.item_name}}</title>
{% endblock %}
{% block body %}
<div class="container" style="background-color:#F7BFB1;">
    <div class="row">
        <div class="col-md-6"> 
            <br><br>
            <img class="card" height="350px" width="450px" src="{{item.item_img}}"/>
        </div>
        <div class="col-md-6">
            <br>
            <h1>{{object.item_name}}</h1>
            <br>
            <h3>{{object.item_desc}}</h3>
            <br>
            <h2>₹{{object.item_price}}</h2>
            <br>
            <h3>Posted by: {{object.user_name}}</h3>
            <br>
            {% if user.is_authenticated %}
            
                <a class="link-danger" href="{% url 'food:delete_item' item.id %}"><input type="button" value="Delete"></a>
                <a class="link-info" href="{% url 'food:update' item.id %}"><input type="button" value="Update"></a>
            {%endif%}
        </div>
    </div>
</div>

{% endblock %}

foodapp/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block head %}
    <title>Menu</title>
{% endblock %}
{% block body %}

    <center><h1 class="display-1">Menu</h1><center><br/>
        <br>
    {% for i in item_list %}
        <div class="row" style="border-style: solid;background-color: #F7BFB1;">
            <div class="col-md-3 offset-md-2">
                <br>
                <img class="card" height="180px" width="250px" src="{{i.item_img}}"/>
                <br>
            </div>
            <div class="col-md-4">
                <br>
                <h3>{{i.item_name}}</h3>
                <h6>₹{{i.item_price}}</h6>
                <h6>Posted by: {{i.user_name}}</h6>
            </div>
            <div class="col-md-2">
                <br>
                <a href="{% url 'food:details' i.id %}" class="btn btn-success">Details</a> 
 
            </div>
        </div>
    {% endfor %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}
        



foodapp/food/templates/food/item_form.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        <h1>Add Item</h1>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {%for i in form%}
                                <div class="form-group">
                                    {{i.name}}
                                    <br>
                                    {{i}}
                                </div>
                            {%endfor%}
                            <br>
                        <button class="btn-info text-white" type="submit">Add Item</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

foodapp/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {%for i in form%}
                                <div class="form-group">
                                    {{i.name}}
                                    <br>
                                    {{i}}
                                </div>
                            {%endfor%}
                            <button class="btn-info text-white" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


foodapp/users/templates/users/logout.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="alert alert-danger" role="alert">
        <center>
        <h1>User Logged out</h1>
        </center>
    </div>
    <a href="{% url 'food:index' %}">Home</a>
{% endblock %}

foodapp/users/templates/users/profile.html
{% extends 'food/base.html' %}
{%block body%}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        <h1>{{ user.username }}</h1>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <h1>{{ user.username }}</h1>
                        <img width="100px" height="100px" src="{{ user.profile.img.url }}">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

foodapp/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            <h1>SignUp</h1>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {%for i in form%}
                                <div class="form-group">
                                    {{i.name}}
                                    <br>
                                    {{i}}
                                </div>
                            {%endfor%}
                            <br>
                            <button class="btn-info text-white" type="submit">Signup</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!--<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Signup</button>
</form>-->